// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Email    string `form:"email"`
	Password string `form:"password"`
}

type RegisterRequest struct {
	Name     string `form:"name"`
	Email    string `form:"email"`
	Password string `form:"password"`
	Vcode    string `form:"vcode"`
}

type BaseResponse struct {
	Message string `json:"message"`
	Ok      bool   `json:"ok"`
}

type LoginResponse struct {
	BaseResponse
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type RegisterResponse struct {
	BaseResponse
}

type LogoutRequest struct {
	Token string `header:"Authorization"`
}

type LogoutResponse struct {
	BaseResponse
}

type RegisterVcodeRequest struct {
	Email string `form:"email"`
}

type RegisterVcodeResponse struct {
	BaseResponse
}

type FileUploadResponse struct {
	BaseResponse
}

type FileUploadRequest struct {
	Parent *uint `form:"parent,optional"`
}

type CreateDirectoryResponse struct {
	BaseResponse
}

type DeleteFileResponse struct {
	BaseResponse
}

type DeleteFileRequest struct {
	UUID string `path:"uuid"`
}

type DeleteFilesRequest struct {
	UUIDs []string `form:"uuids"`
}

type DeleteFilesResponse struct {
	BaseResponse
}

type CreateDirectoryRequest struct {
	Name   string `form:"name,optional"`
	Parent *uint  `form:"parent,optional"`
}

type ShareFileRequest struct {
	ID       uint    `path:"id"`
	Password *string `form:"password, optional"`
	ExpireAt *int64  `form:"expireAt, optional"`
}

type ShareFileResponse struct {
	BaseResponse
}

type DownloadSharedFileRequest struct {
	UUID     string  `path:"uuid"`
	Password *string `form:"password"`
}

type DownloadSharedFileResponse struct {
	BaseResponse
}

type SaveSharedFileRequest struct {
	UUID     string  `path:"uuid"`
	Password *string `form:"password, optional"`
	Name     string  `form:"name, optional"`
}

type SaveSharedFileResponse struct {
	BaseResponse
}

type GetSharedFileRequest struct {
	UUID     string `path:"uuid"`
	Password string `form:"password, optional"`
}

type GetSharedFileResponse struct {
	BaseResponse
	Data *ShareDTO `json:"data"`
}

type DeleteSharedFileResponse struct {
	BaseResponse
}

type DeleteSharedFileRequest struct {
	UUID string `path:"uuid"`
}

type ShareDTO struct {
	ID        uint    `json:"id"`
	UUID      string  `json:"uuid"`
	ExpireAt  *int64  `json:"expireAt"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
	File      FileDTO `json:"file"`
	Username  string  `json:"username"`
	Password  *string `json:"password"`
}

type UpdateFileRequest struct {
	ID      uint   `path:"id"`
	Name    string `form:"name,optional"`
	Private *bool  `form:"private,optional"`
	Parent  *uint  `form:"parent,optional"`
}

type UpdateFileResponse struct {
	BaseResponse
}

type MoveFilesRequest struct {
	IDs    []uint `form:"ids"`
	Parent uint   `form:"parent"`
}

type MoveFilesResponse struct {
	BaseResponse
}

type FileDownloadRequest struct {
	UUID string `path:"uuid"`
}

type UserDTO struct {
	ID    uint   `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Quota int64  `json:"quota"`
	Usage int64  `json:"usage"`
}

type FileDTO struct {
	ID      uint   `json:"id"`
	Name    string `json:"name"`
	Ext     string `json:"ext"`
	Size    int64  `json:"size"`
	UUID    string `json:"uuid"`
	Owner   uint   `json:"owner"`
	IsDir   bool   `json:"isDir"`
	Private bool   `json:"private"`
	Parent  *uint  `json:"parent"`
}

type GetMyFileRequest struct {
	Parent     *uint    `form:"parent,optional"`
	Keyword    string   `form:"keyword,optional"`
	Extensions []string `form:"extensions,optional"`
}

type GetOneFileRequest struct {
	ID uint `path:"id"`
}
