// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cloud_disk/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckBlackList},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/me",
					Handler: MeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/logout",
					Handler: LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
