apiVersion: apps/v1
kind: Deployment
metadata:
  name: disko-backend
spec:
  selector:
    matchLabels:
      app: disko-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: disko-backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -zv mysql 3306; do echo "Waiting for MySQL to start"; sleep 5; done;' ]
        - name: wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -zv redis 6379; do echo "Waiting for Redis to start"; sleep 5; done;' ]
      containers:
        - name: disko-backend
          image: 923048992/disko-backend
          volumeMounts:
            - name: disko-config
              mountPath: /build/etc
            - name: disko-data
              mountPath: /build/data
      volumes:
        - name: disko-config
          hostPath:
            path: /home/disko/deployment/etc
        - name: disko-data
          hostPath:
            path: /home/disko/data
---
apiVersion: v1
kind: Service
metadata:
  name: disko-backend
spec:
  type: NodePort
  ports:
    - name: port8888
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30091
  selector:
    app: disko-backend
